// <auto-generated />
using System;
using DesafioConcrete.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioConcrete.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    [Migration("20200413123308_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioConcrete.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DDD");

                    b.Property<int>("numero");

                    b.HasKey("Id");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("DesafioConcrete.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.Property<int?>("TelefonesId");

                    b.Property<string>("Token");

                    b.Property<DateTime>("UltimoLogin");

                    b.HasKey("Id");

                    b.HasIndex("TelefonesId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DesafioConcrete.Usuario", b =>
                {
                    b.HasOne("DesafioConcrete.Models.Telefone", "Telefones")
                        .WithMany()
                        .HasForeignKey("TelefonesId");
                });
#pragma warning restore 612, 618
        }
    }
}
